[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.39.2", features = ["full"]}
Peer = {path = "../Peer"}
custom_errors = {path = "../custom_errors"}
Commands = {path = "../Commands"}
user = {path = "../user"}
bincode = "1.3.3"