[package]
name = "Commands"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.128"

custom_errors = {path = "../custom_errors"}