[package]
name = "MainServer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.39.2", features = ["full"]}
lazy_static = "1.5.0"
Peer = {path = "../Peer"}
custom_errors = {path = "../custom_errors"}
Commands = {path = "../Commands"}
user = {path = "../user"}